resolver: lts-9.5
packages:
- location: .
- location:
    git: https://github.com/rumblesan/HaskellRaycaster.git
    commit: d73e83fdc7b80d7b24b76f35d1a1d1629858c936
extra-deps: []
flags: {}
extra-package-dbs: []
